<a href="https://colab.research.google.com/github/seunghoona/study-ai-mnist/blob/main/books/basic/1_basic_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install nltk konlpy pandas numpy

In [1]:
import nltk
nltk.download('treebank')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.


True

In [5]:
import pandas as pd
import numpy as np

In [11]:
sr = pd.Series([1700, 18_000, 10_000, 50_000], index=['피자','치킨','콜라','맥주'])
sr

피자     1700
치킨    18000
콜라    10000
맥주    50000
dtype: int64

In [13]:
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one','two','three']
columns = ['A','B','C']
df = pd.DataFrame(values, index=index, columns=columns)
df

A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

# 2차원 배열

In [9]:
mat = np.array([[10,20,30],[60,70,80]])

In [10]:
print(mat)

[[10 20 30]
 [60 70 80]]


In [13]:
print("mat의 축의 개수 :", mat.ndim)
print("mat의 크기(shape)", mat.shape)

mat의 축의 개수 : 2
mat의 크기(shape) (2, 3)


## ndarray의 초기화 
- zeros
- ones
- full
- eye
- random

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.random((3,3))

array([[0.01904341, 0.40292356, 0.04537315],
       [0.27529059, 0.20099611, 0.71312209],
       [0.20450628, 0.50370938, 0.31852628]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# 1qㅜ텉 9 까지 +2씩 적용되는 범위
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [30]:
np.array(np.arange(15)).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Numpy 슬라이싱

In [31]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)


[[1 2 3]
 [4 5 6]]


In [35]:
# 첫번째 행 출력
print(mat[0,:])

# 두번째 열 출력
print(mat[:,1])
# 세번째 열 출력
print(mat[:,2])

[1 2 3]
[2 5]
[3 6]


## 배열간 연산 

In [36]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [40]:
print(x-y)
np.subtract(x, y)

[-3 -3 -3]


array([-3, -3, -3])

In [42]:
print(x*y)
np.multiply(x, y)

[ 4 10 18]


array([ 4, 10, 18])

In [43]:
print(x/y)
np.divide(x, y)

[0.25 0.4  0.5 ]


array([0.25, 0.4 , 0.5 ])

In [49]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
print(mat1 * mat2)
np.dot(mat1, mat2)

[[ 5 12]
 [21 32]]


array([[19, 22],
       [43, 50]])

In [60]:
from sklearn.model_selection import train_test_split
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)
X = np_array[:,:3]
y = np_array[:,3]

print('X 데이터 :')
print(X)
print('y 데이터 :',y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1)

print("X_train", X_train)
print("X_test", X_test)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]
X_train [[ 8  9 10]
 [ 0  1  2]
 [ 4  5  6]]
X_test [[12 13 14]]


In [61]:
# 실습을 위해 임의로 X와 y가 이미 분리 된 데이터를 생성
X, y = np.arange(0,24).reshape((12,2)), range(12)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))


X 전체 데이터 :
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
y 전체 데이터 :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [66]:
num_of_train = int(len(X) * 0.8) # 데이터의 전체 길이의 80%에 해당하는 길이값을 구한다.
num_of_test = int(len(X) - num_of_train) # 전체 길이에서 80%에 해당하는 길이를 뺀다.
print('훈련 데이터의 크기 :',num_of_train)
print('테스트 데이터의 크기 :',num_of_test)

훈련 데이터의 크기 : 9
테스트 데이터의 크기 : 3


In [67]:
X_test = X[num_of_train:] # 전체 데이터 중에서 20%만큼 뒤의 데이터 저장
y_test = y[num_of_train:] # 전체 데이터 중에서 20%만큼 뒤의 데이터 저장
X_train = X[:num_of_train] # 전체 데이터 중에서 80%만큼 앞의 데이터 저장
y_train = y[:num_of_train] # 전체 데이터 중에서 80%만큼 앞의 데이터 저장