<a href="https://colab.research.google.com/github/seunghoona/study-ai-mnist/blob/main/books/basic/1_basic_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install nltk konlpy pandas numpy

In [1]:
import nltk
nltk.download('treebank')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.


True

In [5]:
import pandas as pd
import numpy as np

In [11]:
sr = pd.Series([1700, 18_000, 10_000, 50_000], index=['피자','치킨','콜라','맥주'])
sr

피자     1700
치킨    18000
콜라    10000
맥주    50000
dtype: int64

In [13]:
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one','two','three']
columns = ['A','B','C']
df = pd.DataFrame(values, index=index, columns=columns)
df

A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

# 2차원 배열

In [9]:
mat = np.array([[10,20,30],[60,70,80]])

In [10]:
print(mat)

[[10 20 30]
 [60 70 80]]


In [13]:
print("mat의 축의 개수 :", mat.ndim)
print("mat의 크기(shape)", mat.shape)

mat의 축의 개수 : 2
mat의 크기(shape) (2, 3)


## ndarray의 초기화 
- zeros
- ones
- full
- eye
- random

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.random((3,3))

array([[0.01904341, 0.40292356, 0.04537315],
       [0.27529059, 0.20099611, 0.71312209],
       [0.20450628, 0.50370938, 0.31852628]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# 1qㅜ텉 9 까지 +2씩 적용되는 범위
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [30]:
np.array(np.arange(15)).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])